### ISSUE TITLE
Not Found when installing

### ISSUE THREAD

**Issue by hallysonh-newsela** [flathub/com.getpostman.Postman#112] opened 2021-08-20 19:50 UTC
I am trying to update the Postman on my PopOs Linux, but I am receiving the following message on my terminal:

```sh
Error: While downloading https://dl.pstmn.io/download/version/8.11.0/linux64: Server returned status 404: Not Found
error: Failed to install com.getpostman.Postman: While downloading https://dl.pstmn.io/download/version/8.11.0/linux64: Server returned status 404: Not Found
```

I googled this issue and found [this topic](https://github.com/postmanlabs/postman-app-support/issues/7395#issuecomment-537572867) stating that the issue is occurring because this package is out of date.

**Comment by ghisvail** [comment] 2021-08-20 19:52
Duplicate of #111 fixed with latest commit. Please check past issues before posting next time.

**Closed by ghisvail** 2021-08-20 19:52 UTC
Labels: duplicate
