### ISSUE TITLE
Update to version 9.0.2?

### ISSUE THREAD

**Issue by rafaelmartines** [flathub/com.getpostman.Postman#126] opened 2021-09-21 01:58 UTC
Its has been a while since the version 9.0.2 came out, is there any ETA?

**Comment by ghisvail** [comment] 2021-09-21 06:09
I dont see it listed here:

https://www.postman.com/downloads/release-notes/

**Comment by ghisvail** [comment] 2021-09-21 13:54
Looks like version `9.0.3` was released today so the autoupdater should pick it up. Please be patient.

**Comment by rafaelmartines** [comment] 2021-09-21 19:04
> Looks like version `9.0.3` was released today so the autoupdater should pick it up. Please be patient.

They just updated to 8.11 and the version I installed via flathub was 8.12 🙃

**Comment by ghisvail** [comment] 2021-09-22 10:30
> They just updated to 8.11 and the version I installed via flathub was 8.12 upside_down_face

Fun fact, the Postman public API still points to version 8.11 although 9.0.3 is available. I have switched the release monitoring to parse the official release notes (#128) as a result.

**Comment by rafaelmartines** [comment] 2021-09-30 00:17
Looking flathub.json I see this https://dl.pstmn.io/download/version/8.11.1/linux64

Is it generated? Because this url is working https://dl.pstmn.io/download/version/9.0.3/linux64

**Comment by ghisvail** [comment] 2021-09-30 05:32
No need to duplicate posts. Stick to one.

**Comment by nhubaotruong** [comment] 2021-09-30 18:20
Hi, I found this update check url from within the Postman app:
https://dl.pstmn.io/update/status?channel=stable&currentVersion=9.0.2&arch=64&platform=linux (currentVersion is something newer than `8.11.1` and it will return the latest version)
The old api https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable is forever stuck at `8.11.1`

**Comment by ghisvail** [comment] 2021-09-30 21:57
I don't get it, what's the URL for the latest stable version then?

**Comment by nhubaotruong** [comment] 2021-10-01 01:15
There is no "latest" url at the moment, the best thing I could find is that update check url, which actually returns the "latest" version

**Comment by ghisvail** [comment] 2021-10-01 07:36
> There is no "latest" url at the moment

Then, it's a severe regression from the previous API.

Is there anyone from Postman we could speak to in order to get a proper latest version available check that does not change every now and then?

**Comment by nhubaotruong** [comment] 2021-10-01 08:24
>https://dl.pstmn.io/update/status?channel=stable&currentVersion=9.0.2&arch=64&platform=linux 

Can't we use the update check url ?

It also returns latest version number

**Comment by ghisvail** [comment] 2021-10-01 10:41
It's not officially released yet:

https://twitter.com/NumaanAshraf/status/1443848424256798725?s=19

Le ven. 1 oct. 2021 à 10:24, Như Bảo Trương ***@***.***> a
écrit :

**Comment by nhubaotruong** [comment] 2021-10-01 10:44
Then why is it prompting users to update in-app though :thinking: .

I guess we should wait and see.

**Comment by ghisvail** [comment] 2021-10-01 10:52
Yes, I suspect the app uses the status API you mentioned, whilst the
website uses the release API currently used for this flatpak and the
official download page.

I guess all we have to do is wait.

Le ven. 1 oct. 2021 à 12:44, Như Bảo Trương ***@***.***> a
écrit :

**Comment by ghisvail** [comment] 2021-10-02 11:35
Now available in the beta release channel, see here: https://github.com/flathub/com.getpostman.Postman/pull/131

**Comment by cho2** [comment] 2021-10-04 02:27
I switch to flathub-beta, the version in flatpak info still `8.12.4` although the version in the app is `9.0.3`

```
flatpak info com.getpostman.Postman

Postman - Postman is a complete API development environment.

        ID: com.getpostman.Postman
       Ref: app/com.getpostman.Postman/x86_64/beta
Arsitektur: x86_64
    Cabang: beta
     Versi: 8.12.4
   Lisensi: LicenseRef-proprietary
      Asal: flathub-beta
   Koleksi: org.flathub.Beta
Pemasangan: user
 Terpasang: 3,8 MB
   Runtime: org.freedesktop.Platform/x86_64/21.08
       Sdk: org.freedesktop.Sdk/x86_64/21.08

     Komit: 2a9efb83708559ad1cae3a97f6f92cb7a35c9b5efb34ea5488a26444a7283339
    Subjek: Switch branch to beta (e91b80fa)
   Tanggal: 2021-10-02 11:36:03 +0000
```

![Cuplikan layar dari 2021-10-04 09-27-02](https://user-images.githubusercontent.com/6271071/135784668-caa832fa-e168-46ca-b2ec-4a0338cb825a.png)

**Comment by ghisvail** [comment] 2021-10-04 05:25
I have just updated it to version 9.0.5 which fixes an issue with LE certificates.

**Comment by atrauzzi** [comment] 2021-10-14 17:15
@ghisvail -  Tried this, but no luck:

![image](https://user-images.githubusercontent.com/115199/137365200-48305c28-7be5-4bfa-a1c9-cd0b690517f6.png)

**Comment by ghisvail** [comment] 2021-10-15 14:42
Could you submit a PR on the beta branch which corrects the size of the
Postman source?

Cheers,

**Comment by atrauzzi** [comment] 2021-10-15 14:45
I'm not a flatpak expert, nor do I know what the correct size is.

**Comment by dylanmtaylor** [comment] 2021-10-16 23:13
Looks like 9.0.7 is out and the flathub version is lagging behind by quite a bit still.

**Comment by CodeDead** [comment] 2021-10-17 00:08
> Looks like 9.0.7 is out and the flathub version is lagging behind by quite a bit still.

Even on the official postman site, they still point their latest download to v8.12.4 (even for Windows):
https://www.postman.com/downloads/

Odd, to say the least.

**Comment by dkarlovi** [comment] 2021-11-04 09:23
How are the versions detected? They have version 9.1.3 released here:
https://www.postman.com/downloads/release-notes/

**Comment by ghisvail** [comment] 2021-11-04 09:35
The official version for Linux still is `8.12.5`: https://www.postman.com/downloads/

**Comment by ghisvail** [comment] 2021-11-04 15:10
I stand corrected, Postman did it again and rolled it back to `8.12.4`. Because well, Postman.

**Comment by ghisvail** [comment] 2021-11-04 15:12
@dkarlovi I'll happily accept a PR for an update to version `9.1.3` on the beta channel.

See https://github.com/flathub/com.getpostman.Postman/pull/135 for an example.

**Comment by apahne** [comment] 2021-11-18 08:28
Also don't want to create pressure here, but I would like to say, that it would be nice to be able to install Postman 9.x with flatpak. Really looking forward to be using the nice new features of Postman 9.

**Comment by mijorus** [comment] 2021-11-18 08:31
> Also don't want to create pressure here, but I would like to say, that it would be nice to be able to install Postman 9.x with flatpak. Really looking forward to be using the nice new features of Postman 9.

I believe that Postman 9 is just a re branded name for Postman 8.12.x If you go on the official website, the package is still labeled 8.12.x when you download it.

**Comment by dkarlovi** [comment] 2021-11-18 08:46
> I believe that Postman 9 is just a re branded name for Postman 8.12.x

I don't believe this is the case, if you check the release notes, the 9.x branch lists a lot of features.

**Comment by ghisvail** [comment] 2021-11-18 09:45
> Also don't want to create pressure here [...]

But you are doing it anyway.

> it would be nice to be able to install Postman 9.x with flatpak

You can, using the beta channel.

> Postman 9 is just a re branded name for Postman 8.12.x

Did you ask for confirmation of this statement from a Postman official?

I asked on Twitter, and their reply was 8.12.x remains the official release for MacOS and Linux.

Now, can we just wait patiently and go on with our lives please?

**Comment by mijorus** [comment] 2021-11-18 15:33
> Did you ask for confirmation of this statement from a Postman official?

In my comment, I said that it was my own conclusion, since on their website they are showing off how cool their new version is but the package that you download is still called 8.12. I couldn't get my head around that.

Anyway, thanks for having clarified it. We just have to live with the annoying modal at startup.

**Comment by dkarlovi** [comment] 2021-11-19 12:55
> I asked on Twitter, and their reply was 8.12.x remains the official release for MacOS and Linux.

@ghisvail got a link?

**Comment by valdeir2000** [comment] 2021-11-19 13:52
The version has been updated on the website.

![image](https://user-images.githubusercontent.com/606481/142633331-7bb95115-f6ee-443b-9588-98b9f8d55e3e.png)

**Comment by ghisvail** [comment] 2021-11-19 14:00
Closed by https://github.com/flathub/com.getpostman.Postman/pull/141

**Closed by ghisvail** 2021-11-19 14:00 UTC
